# Christopher Iliffe Sprague
# sprague@kth.se

language: python
python:
  - 3.6
install: python setup.py install
script: jupyter nbconvert --ExecutePreprocessor.timeout=-1 --to notebook --execute notebooks/tutorial.ipynb
