language: python

python:
- 3.6

install:
  - pip install .

script:
  - jupyter nbconvert --ExecutePreprocessor.timeout=-1 --to notebook --execute notebooks/tutorial.ipynb

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
  git checkout --orphan gh-pages
  git rm -rf --cached .
  git submodule add https://github.com/hakimel/reveal.js.git reveal.js
  jupyter nbconvert notebooks/tutorial.ipynb --to slides --reveal-prefix reveal.js
  mv notebooks/tutorial.slides.html index.html
  git add -f --ignore-errors index.html reveal.js
  git -c user.name='travis' -c user.email='travis' commit -m init
  git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG gh-pages
  cd ..
  rm -R tmp
  fi
